### PR TITLE
Improvements and fixes in sphinx doc generation

### PR DESCRIPTION
**Pull request by denisri**

### CODE REVIEW

**Comment by AGrigis** [comment]
1) In order to be consitenor with the output option,it is necessary to modify capsul_pipeline_view, capsul_sphinx_layout, and capsul_usecases_rst the same way.
2) Would it be better to use the trait filtering option (it simplify the synthax)? This would request to modify the trait creation by setting default values for the optional and output trait parameters.

**Comment by denisri** [comment]
1) I was just testing the docs with morphologist processes, which are not available in capsulview, and my doc has a different tree structure (for now, at least), that's why I wanted this output option.
2) I tried to use traits(output=None) first, but this returns not only user traits but also non-user ones, so it needed manual filtering via iteration also, and seemed more complex and less straightforward to me (make a 1st dict using traits(output=False), update it using taits(output=None), then filter out traits not in user_traits()...)

**Comment by AGrigis** [comment]
1) I can't validate this pull request since all the codes are consistent.
2) You may prefer to modify the capsul trait creation by setting default values for the optional and output trait parameters: for instance optional=False, output=False.

**Comment by denisri** [comment]
1) offering this option is also a way to document where things will be done: it was not ovious that .rst files are generated in "$CWD/source/generated/...". The default is still the same as it used to be so it doesn't break anything, and allows some customization, so I find it clearer with the option.
2) It would need to overload (or modify overloads of) add_trait on Process, Pipeline, (and possibly pipeline nodes elements? - maybe not needed) to ensure all user_traits always have the output and optional attributes. That would probably be possible, assuming that non-user traits never specify output/optional (I guess it is OK). We could do that later.

**Pull request merged**
